# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - run: npm run test:unit
    - run: npm run test:e2e
  notify_failture:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      if: always()&& needs.build.result == 'failure'
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: '@everyone The project {{ EVENT_PAYLOAD.repository.full_name }} has error. Error on test step'
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: needs.build.result == 'success'
    continue-on-error: true
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 2137
        script: |
          cd /srv/coypos-ui
          git pull origin master
          git status
          npm install
          npm run build
          sudo rm -r /var/www/coypos/*
          sudo cp -r /srv/coypos-ui/dist/* /var/www/coypos/
  notify_failture2:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      if: always() && needs.deploy.result == 'failure'
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: '@everyone The project {{ EVENT_PAYLOAD.repository.full_name }} has error. Error on deploy step'
  notify_success:
    needs: deploy
    if: needs.deploy.result == 'success'
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
 
