# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - run: npm run test:unit
    - run: npm run test:e2e
    - name: Notify discord
      uses: th0th/notify-discord@v0.4.1
      if: ${{ always() }}
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_JOB_NAME: "Testy jednostkowe i e2e"
        GITHUB_JOB_STATUS: ${{ job.status }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 2137
        script: |
          cd /srv/coypos-ui
          git pull origin master
          git status
          npm install
          npm run build
          sudo rm -r /var/www/coypos/*
          sudo cp -r /srv/coypos-ui/dist/* /var/www/coypos/
    - name: Notify discord
      uses: th0th/notify-discord@v0.4.1
      if: ${{ always() }}
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_JOB_NAME: "Deploy na serwer"
        GITHUB_JOB_STATUS: ${{ job.status }}
